export const FETCH = "USER/FETCH";
export const FETCHED = "USER/FETCHED";
export const FETCH_FAILED = "USER/FETCH_FAILED";

export const ADD_POINTS = "USER/ADD_POINTS";
export const GIVE_BADGE = "USER/GIVE_BADGE";
export const COMPLETE_QUESTION = "USER/COMPLETE_QUESTION";
export const INCREASE_QUESTIONS_COMPLETED = "USER/INCREASE_QUESTIONS_COMPLETED";